<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create category' => 'دسته بندی بساز', 
    'Edit category' => 'ویرایش دسته بندی',
    'Logout' => 'خروج',
    'Open site' => 'سایت عمومی را باز کن',
    'Add' => 'اضافه',
    'Categories' => 'دسته بندی ها',
    'Clear image' => 'عکس را پاک کن',
    'Create' => 'بساز',
    'Create error. {0}' => 'خطای ساخت. {0}',
    'Date' => 'تاریخ',
    'Delete item' => 'آیتم را پاک کن',
    'Image' => 'تصویر',
    'Image cleared' => 'تصویر پاک شد',
    'Link' => 'لینک',
    'List' => 'لیست',
    'Move down' => 'برو پایین',
    'Move up' => 'برو بالا',
    'No records found' => 'موردی پیدا نشد',
    'Not found' => 'پیدا نشد',
    'Photos' => 'عکس ها',
    'Save' => 'دخیره',
    'Slug' => 'اسلاگ',
    'Slug can contain only 0-9, a-z and "-" characters (max: 128).' => 'اسلاگ فقط می تواند شامل اعداد، حروف کوچک لاتین، و "-" باشد و حداکثر 128 کاراکتر داشته باشد.',
    'Status' => 'وضعیت',
    'Tags' => 'برچسب ها',
    'Text' => 'متن',
    'Title' => 'عنوان',
    'Update error. {0}' => 'خطای ویرایش. {0}',
    'Views' => 'بازدیدها',
];
