<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    
    'Create text' => 'قطعه متنی بساز',
    'Text created' => 'قطعه متنی ساخته شد',
    

//Copied from messages of noumo

    'Control Panel' => 'پنل مدیرت',
    'Welcome' => 'خوش آمدید',
    'Welcome to control panel, choose which section you want to manage in left menu.' => 'به پنل مدیریت خوش آمدید، لطفا از منوی سمت راست قسمت مورد نظر خود را انتخاب کنید.',
    'Incorrect username or password.' => 'نام کاربری یا رمز عبور اشتباه است.',
    'You tried to login too often. Please wait 5 minutes.' => 'بیش از حد مجاز برای ورود تلاش کردید. لطفا 5 دقیقه صبر کنید.',
    'Class does not exist' => 'کلاس وجود ندارد',
    'Open site' => 'سایت عمومی را باز کن',
    'Live edit' => 'ویرایش زندهبی',
    'Username' => 'نام کاربری',
    'Password' => 'رمز عبور',
    'Remember me' => 'مرا به یاد بسپار',
    'Link' => 'لینک',
    'Icon' => 'آیکن',
    'Class' => 'کلاس',
    'Order' => 'سفارش',
    'Value' => 'مقدار',
    'Sign in' => 'ورود',
    'Login' => 'ورود',
    'Logout' => 'خروج',
    'List' => 'لیست',
    'Create' => 'بساز',
    'Title' => 'عنوان',
    'Name' => 'نام',
    'Text' => 'متن',
    'Date' => 'تاریخ',
    'Slug' => 'اسلاگ',
    'Tags' => 'برچسب ها',
    'Status' => 'وضعیت',
    'Image' => 'عکس',
    'File' => 'فایل',
    'Views' => 'نماها',
    'Description' => 'توضیحات',
    'Delete item' => 'آیتم را حذف کن',
    'No records found' => 'موردی پیدا نشد',
    'Save' => 'دخیره کن',
    'Send' => 'ارسال کن',
    'Upload' => 'آپلود',
    'Modules' => 'ماژول',
    'Settings' => 'تنظیمات',
    'Back' => 'عقب',
    'Go back' => 'برگرد به عقب',
    'New' => 'تازه',
    'All' => 'همه',
    'Yes' => 'بله',
    'No' => 'خیر',
    'Add' => 'اضافه کن',
    'Edit' => 'ویرایش کن',
    'Copy' => 'کپی کن',
    'Update' => 'ویراایش کن',
    'Move down' => 'برو پایین',
    'Move up' => 'برو بالا',
    'Delete' => 'پاک کن',
    'Turn On' => 'روشن کن',
    'Turn Off' => 'خاموش کن',
    'Status successfully changed' => 'وضعیت با موفقیت تغییر کرد.',
    'Add subcategory' => 'زیردسته اضافه کن',
    'Anti-spam check' => 'چک ضد اسپم',
    'Actions' => 'عمل ها',

    'Not found' => 'پیدا نشد',
    'Create error. {0}' => 'خطای ساخت {0}',
    'Update error. {0}' => 'خطای ویرایش {0}',
    'An error has occurred' => 'خطایی اتفاق افتاد',
    'Slug can contain only 0-9, a-z and "-" characters (max: 128).' => 'اسلاگ فقط می تواند شامل حروف لاتین، اعداد، و "-" باشد. همیچنین تعداد کاراکتر ها حداکثر 128 تا می توانند باشند.',

    'Only for developer' => 'فقط برای توسعه دهند ها',
    'Create setting' => 'تنظیمات بساز',
    'Edit setting' => 'ویرایش بساز',
    'Setting created' => 'تنظیمات ساخته شد',

    'Setting updated' => 'تنظیمات ویرایش شد',
    'Setting deleted' => 'تنظیمات پاک شد',

    'Basic' => 'پایه',
    'Advanced' => 'پیشرفته',
    'Create module' => 'ماژول بساز',
    'Edit module' => 'ویرایش ماژول',
    'module doesn`t have any settings.' => 'ماژول هیچ تنظیماتی ندارد.',
    'Restore default settings' => 'تنظیمات پیشفرض را بازگردان',
    'Module created' => 'ماژول ساخته شد',
    'Module updated' => 'ماژول ویرایش شد',
    'Module deleted' => 'ماژول پاک شد',
    'Module settings updated' => 'تنظیمات ماژول ویرایش شد',
    'Module default settings was restored' => 'تنظیمات پیشفرض ماژول بازگردانده شد',

    'Admins' => 'ادمین ها',
    'Create admin' => 'ادمین بساز',
    'Edit admin' => 'ادمین را ویرایش کن',
    'Admin created' => 'ادمین ساخته شد',
    'Admin updated' => 'ادمین ویرایش شد',
    'Admin deleted' => 'ادمین پاک شد',

    'Photos' => 'عکس ها',
    'Photo count' => 'تعداد عکس ها',
    'Photo description saved' => 'توضیحات عکس ذخیره شد',
    'Photo deleted' => 'عکس پاک شد',
    'Photo uploaded' => 'عکس بارگذاری شد',
    'No photos uploaded yet' => 'هنوز هیچ عکسی بارگذاری نشده است',
    'Bad response' => 'واکنش بد',
    'File is incorrect' => 'فایل نادرست است',
    'File upload error. Check uploads folder for write permissions' => 'خطا در بارگذاری فایل. سطح دسترسی پوشه بارگذاری را چک کنید.',
    'Change image' => 'تغییر عکس',
    'Uploading. Please wait' => 'درحال بارگذاری. لطفا منتظر بمانید.',

    'System' => 'سیستم',
    'Current version' => 'نسخه فعلی',
    'Flush cache' => 'تخلیه کش',
    'Clear assets' => 'پاک کردن اسِتها',
    'Assets cleared' => 'اسِتها پاک شدند',
    'Cache flushed' => 'کش تخلیه شد',
    'Logs' => 'لاگ ها',
    'Seo texts' => 'متنهای سئو',

    'Categories' => 'دسته بندی ها',
    'Create category' => 'دسته بندی بساز',
    'Edit category' => 'دسته بندی ویرایش کن',
    'Category created' => 'دسته بندی ساخته شد',
    'Category updated' => 'دسته بندی ویرایش شد',
    'Category deleted' => 'دسته بندی پاک شد',
    'Category image cleared' => 'عکس دسته بندی پاک شد',

    'Clear image' => 'عکس را پاک کن',
    'Image cleared' => 'عکس پاک شد',
];
