<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(not set)' => '',
    'No' => '',
    'Yes' => '',
    'in {delta, plural, =1{a day} other{# days}}' => '',
    'in {delta, plural, =1{a minute} other{# minutes}}' => '',
    'in {delta, plural, =1{a month} other{# months}}' => '',
    'in {delta, plural, =1{a second} other{# seconds}}' => '',
    'in {delta, plural, =1{a year} other{# years}}' => '',
    'in {delta, plural, =1{an hour} other{# hours}}' => '',
    'just now' => '',
    '{attribute} cannot be blank.' => '',
    '{delta, plural, =1{1 day} other{# days}}' => '',
    '{delta, plural, =1{1 hour} other{# hours}}' => '',
    '{delta, plural, =1{1 minute} other{# minutes}}' => '',
    '{delta, plural, =1{1 month} other{# months}}' => '',
    '{delta, plural, =1{1 second} other{# seconds}}' => '',
    '{delta, plural, =1{1 year} other{# years}}' => '',
    '{delta, plural, =1{a day} other{# days}} ago' => '',
    '{delta, plural, =1{a minute} other{# minutes}} ago' => '',
    '{delta, plural, =1{a month} other{# months}} ago' => '',
    '{delta, plural, =1{a second} other{# seconds}} ago' => '',
    '{delta, plural, =1{a year} other{# years}} ago' => '',
    '{delta, plural, =1{an hour} other{# hours}} ago' => '',
    '{nFormatted} B' => '',
    '{nFormatted} GB' => '',
    '{nFormatted} GiB' => '',
    '{nFormatted} KiB' => '',
    '{nFormatted} MB' => '',
    '{nFormatted} MiB' => '',
    '{nFormatted} PB' => '',
    '{nFormatted} PiB' => '',
    '{nFormatted} TB' => '',
    '{nFormatted} TiB' => '',
    '{nFormatted} kB' => '',
    '{nFormatted} {n, plural, =1{byte} other{bytes}}' => '',
    '{nFormatted} {n, plural, =1{gibibyte} other{gibibytes}}' => '',
    '{nFormatted} {n, plural, =1{gigabyte} other{gigabytes}}' => '',
    '{nFormatted} {n, plural, =1{kibibyte} other{kibibytes}}' => '',
    '{nFormatted} {n, plural, =1{kilobyte} other{kilobytes}}' => '',
    '{nFormatted} {n, plural, =1{mebibyte} other{mebibytes}}' => '',
    '{nFormatted} {n, plural, =1{megabyte} other{megabytes}}' => '',
    '{nFormatted} {n, plural, =1{pebibyte} other{pebibytes}}' => '',
    '{nFormatted} {n, plural, =1{petabyte} other{petabytes}}' => '',
    '{nFormatted} {n, plural, =1{tebibyte} other{tebibytes}}' => '',
    '{nFormatted} {n, plural, =1{terabyte} other{terabytes}}' => '',
];
